export const employeeSheetHeaders = [
  "Cód",
  "Nome",
  "Endereço",
  "Telefone",
  "Celular",
  "Nome da Mãe",
  "Nome do Pai",
  "E-mail",
  "Data de Nascimento",
  "País de Origem",
  "Naturalidade",
  "Deficiência (Tipo)",
  "Raça/Cor",
  "Sexo",
  "Estado Civil",
  "Tipo Sanguíneo",
  "Local",
  "Departamento",
  "Setor",
  "Seção",
  "Data Admissão",
  "Data Exame Médico",
  "Validade Exame Médico (meses)",
  "Data de Saída",
  "Sindicato Representante",
  "Categoria Normativa Vinculada",
  "Tipo de Contrato",
  "Salário",
  "Função",
  "CBO",
  "Data Alteração do Cargo",
  "Horário",
  "Banco",
  "Agência",
  "Tipo da Conta",
  "Número da Conta",
  "Nacionalidade",
  "Grau de Instrução",
  "CTPS/Série/UF",
  "Título de Eleitor/Zona/Seção",
  "PIS",
  "RG",
  "CPF",
  "Número CNH",
  "Categoria CNH",
  "Data Expedição CNH",
  "Órgão Emissor CNH",
  "Validade CNH",
  "Número RIC",
  "Data Expedição RIC",
  "Órgão Emissor RIC",
  "Município RIC",
  "UF RIC",
  "Tipo Documento Militar",
  "Nro. Reservista",
  "Categoria Militar",
  "Data Emissão Certidão Civil",
  "Tipo de Certidão Civil",
  "Termo/Matrícula",
  "Município Certidão Civil",
  "UF Certidão Civil",
  "Cartório Certidão Civil",
  "Livro Certidão Civil",
  "Folha Certidão Civil",
  "Nome Conselho Regional",
  "Sigla Conselho Regional",
  "Número Conselho Regional",
  "Região Conselho Regional",
  "Data Expedição Conselho Regional",
  "Órgão Emissor Conselho Regional",
  "Data Vencimento Conselho Regional",
  "Número RNE",
  "Data Expedição RNE",
  "Órgão Emissor RNE",
  "Validade RNE",
  "Número CTPS Exterior",
  "Data Expedição CTPS Exterior",
  "Validade CTPS Exterior",
  "Tipo de Visto",
  "Número Passaporte",
  "Órgão Emissor Passaporte",
  "UF Passaporte",
  "País Emissor Passaporte",
  "Data Emissão Passaporte",
  "Data Validade Passaporte",
  "Número CNV",
  "Data Expedição CNV",
  "Validade CNV",
  "Residência Própria",
  "Imóvel adquirido com Recurso do FGTS",
  "CNPJ Vínculo Anterior",
  "Matrícula Vínculo Anterior",
  "Data Inicio Vínculo Anterior",
  "Data Fim Vínculo Anterior",
  "Data Inicio Aposentadoria",
  "Motivo Aposentadoria",
  "Instituiçao de Ensino",
  "Coordenador",
  "Agente de Integração",
  "Natureza do Estágio",
  "Seguradora",
  "Número Apólice Seguro",
  "Previsão Término do Estágio",
  "Área de Atuação",
  "Registro de Funcionário",
  "Folha/Ficha",
  "Orgão Emissor do RG",
  "Orgão Emissor RG - Complemento",
  "UF do RG",
  "Data de Expedicao do RG",
  "Evento eSocial",
  "Matrícula eSocial",
  "Operação eSocial",
  "Status eSocial",
  "Nro Recibo eSocial",
  "Nro Protocolo eSocial",
  "Antecipar Indenização do FGTS",
  "Grau de Risco",
] as const

export const dependentSheetHeaders = [
  "Código",
  "Nome do Parentesco",
  "CPF",
  "Grau de Parentesco",
  "Nascimento",
  "Data de Entrega do Registro",
] as const

function formatDate(value: unknown) {
  if (!value || typeof value !== "string") return ""
  if (!value.trim()) return ""
  const parts = value.split("-")
  return parts.length === 3 ? `${parts[2]}/${parts[1]}/${parts[0]}` : value
}

function formatBoolean(value: unknown) {
  return value ? "Sim" : "Não"
}

function asText(value: unknown) {
  return value === null || value === undefined ? "" : String(value)
}

function buildAddress(data: Record<string, unknown>) {
  return [
    data.logradouro,
    data.numero,
    data.complemento,
    data.bairro,
    data.cidade,
    data.uf,
    data.cep,
  ]
    .map(asText)
    .map((item) => item.trim())
    .filter(Boolean)
    .join(", ")
}

export function buildEmployeeSheetRow(data: Record<string, unknown>) {
  return {
    "Cód": asText(data.codigo_funcionario || data.id_externo || ""),
    "Nome": asText(data.nome_completo),
    "Endereço": buildAddress(data),
    "Telefone": asText(data.telefone),
    "Celular": asText(data.celular),
    "Nome da Mãe": asText(data.nome_mae),
    "Nome do Pai": asText(data.nome_pai),
    "E-mail": asText(data.email),
    "Data de Nascimento": formatDate(data.data_nascimento),
    "País de Origem": asText(data.pais_origem),
    "Naturalidade": asText(data.naturalidade),
    "Deficiência (Tipo)": asText(data.deficiencia_tipo),
    "Raça/Cor": asText(data.raca_cor),
    "Sexo": asText(data.sexo),
    "Estado Civil": asText(data.estado_civil),
    "Tipo Sanguíneo": asText(data.tipo_sanguineo),
    "Local": asText(data.local),
    "Departamento": asText(data.departamento),
    "Setor": asText(data.setor),
    "Seção": asText(data.secao),
    "Data Admissão": formatDate(data.data_admissao),
    "Data Exame Médico": formatDate(data.data_exame_medico),
    "Validade Exame Médico (meses)": asText(data.validade_exame_medico),
    "Data de Saída": formatDate(data.data_saida),
    "Sindicato Representante": asText(data.sindicato),
    "Categoria Normativa Vinculada": asText(data.categoria_normativa),
    "Tipo de Contrato": asText(data.tipo_contrato),
    "Salário": asText(data.salario),
    "Função": asText(data.cargo),
    "CBO": asText(data.cbo),
    "Data Alteração do Cargo": formatDate(data.data_alteracao_cargo),
    "Horário": asText(data.horario),
    "Banco": asText(data.banco),
    "Agência": asText(data.agencia),
    "Tipo da Conta": asText(data.tipo_conta),
    "Número da Conta": asText(data.numero_conta),
    "Nacionalidade": asText(data.nacionalidade),
    "Grau de Instrução": asText(data.grau_instrucao),
    "CTPS/Série/UF": [data.ctps_numero, data.ctps_serie, data.ctps_uf].map(asText).filter(Boolean).join("/"),
    "Título de Eleitor/Zona/Seção": asText(data.titulo_eleitor),
    "PIS": asText(data.pis),
    "RG": asText(data.rg_numero),
    "CPF": asText(data.cpf),
    "Número CNH": asText(data.cnh_numero),
    "Categoria CNH": asText(data.categoria_cnh),
    "Data Expedição CNH": formatDate(data.data_expedicao_cnh),
    "Órgão Emissor CNH": asText(data.orgao_emissor_cnh),
    "Validade CNH": formatDate(data.validade_cnh),
    "Número RIC": asText(data.numero_ric),
    "Data Expedição RIC": formatDate(data.data_expedicao_ric),
    "Órgão Emissor RIC": asText(data.orgao_emissor_ric),
    "Município RIC": asText(data.municipio_ric),
    "UF RIC": asText(data.uf_ric),
    "Tipo Documento Militar": asText(data.tipo_documento_militar),
    "Nro. Reservista": asText(data.numero_reservista),
    "Categoria Militar": asText(data.categoria_militar),
    "Data Emissão Certidão Civil": formatDate(data.data_emissao_certidao_civil),
    "Tipo de Certidão Civil": asText(data.tipo_certidao_civil),
    "Termo/Matrícula": asText(data.termo_matricula_certidao),
    "Município Certidão Civil": asText(data.municipio_certidao_civil),
    "UF Certidão Civil": asText(data.uf_certidao_civil),
    "Cartório Certidão Civil": asText(data.cartorio_certidao_civil),
    "Livro Certidão Civil": asText(data.livro_certidao_civil),
    "Folha Certidão Civil": asText(data.folha_certidao_civil),
    "Nome Conselho Regional": asText(data.nome_conselho_regional),
    "Sigla Conselho Regional": asText(data.sigla_conselho_regional),
    "Número Conselho Regional": asText(data.numero_conselho_regional),
    "Região Conselho Regional": asText(data.regiao_conselho_regional),
    "Data Expedição Conselho Regional": formatDate(data.data_expedicao_conselho_regional),
    "Órgão Emissor Conselho Regional": asText(data.orgao_emissor_conselho_regional),
    "Data Vencimento Conselho Regional": formatDate(data.data_vencimento_conselho_regional),
    "Número RNE": asText(data.numero_rne),
    "Data Expedição RNE": formatDate(data.data_expedicao_rne),
    "Órgão Emissor RNE": asText(data.orgao_emissor_rne),
    "Validade RNE": formatDate(data.validade_rne),
    "Número CTPS Exterior": asText(data.numero_ctps_exterior),
    "Data Expedição CTPS Exterior": formatDate(data.data_expedicao_ctps_exterior),
    "Validade CTPS Exterior": formatDate(data.validade_ctps_exterior),
    "Tipo de Visto": asText(data.tipo_visto),
    "Número Passaporte": asText(data.numero_passaporte),
    "Órgão Emissor Passaporte": asText(data.orgao_emissor_passaporte),
    "UF Passaporte": asText(data.uf_passaporte),
    "País Emissor Passaporte": asText(data.pais_emissor_passaporte),
    "Data Emissão Passaporte": formatDate(data.data_emissao_passaporte),
    "Data Validade Passaporte": formatDate(data.data_validade_passaporte),
    "Número CNV": asText(data.numero_cnv),
    "Data Expedição CNV": formatDate(data.data_expedicao_cnv),
    "Validade CNV": formatDate(data.validade_cnv),
    "Residência Própria": formatBoolean(data.possui_residencia_propria),
    "Imóvel adquirido com Recurso do FGTS": formatBoolean(data.imovel_fgts),
    "CNPJ Vínculo Anterior": asText(data.cnpj_vinculo_anterior),
    "Matrícula Vínculo Anterior": asText(data.matricula_anterior),
    "Data Inicio Vínculo Anterior": formatDate(data.data_inicio_vinculo_anterior),
    "Data Fim Vínculo Anterior": formatDate(data.data_fim_vinculo_anterior),
    "Data Inicio Aposentadoria": formatDate(data.inicio_aposentadoria),
    "Motivo Aposentadoria": asText(data.motivo_aposentadoria),
    "Instituiçao de Ensino": asText(data.instituicao_ensino),
    "Coordenador": asText(data.coordenador),
    "Agente de Integração": asText(data.agente_integracao),
    "Natureza do Estágio": asText(data.natureza_estagio),
    "Seguradora": asText(data.seguradora),
    "Número Apólice Seguro": asText(data.numero_apolice_seguro),
    "Previsão Término do Estágio": formatDate(data.previsao_termino_estagio),
    "Área de Atuação": asText(data.area_atuacao),
    "Registro de Funcionário": asText(data.registro_funcionario),
    "Folha/Ficha": asText(data.folha_ficha),
    "Orgão Emissor do RG": asText(data.rg_orgao_emissor),
    "Orgão Emissor RG - Complemento": asText(data.rg_orgao_emissor_complemento),
    "UF do RG": asText(data.uf_rg),
    "Data de Expedicao do RG": formatDate(data.rg_data_expedicao),
    "Evento eSocial": asText(data.evento_esocial),
    "Matrícula eSocial": asText(data.matricula_esocial),
    "Operação eSocial": asText(data.operacao_esocial),
    "Status eSocial": asText(data.status_esocial),
    "Nro Recibo eSocial": asText(data.numero_recibo_esocial),
    "Nro Protocolo eSocial": asText(data.numero_protocolo_esocial),
    "Antecipar Indenização do FGTS": formatBoolean(data.antecipar_indenizacao_fgts),
    "Grau de Risco": asText(data.grau_risco),
  } as Record<(typeof employeeSheetHeaders)[number], string>
}

export function buildDependentSheetRows(dependents?: Array<Record<string, unknown>>) {
  if (!dependents?.length) {
    return [
      {
        "Código": "",
        "Nome do Parentesco": "",
        "CPF": "",
        "Grau de Parentesco": "",
        "Nascimento": "",
        "Data de Entrega do Registro": "",
      },
    ]
  }

  return dependents.map((dependent) => ({
    "Código": asText(dependent.codigo),
    "Nome do Parentesco": asText(dependent.nome_parentesco),
    "CPF": asText(dependent.cpf),
    "Grau de Parentesco": asText(dependent.grau_parentesco),
    "Nascimento": formatDate(dependent.nascimento),
    "Data de Entrega do Registro": formatDate(dependent.data_entrega_registro),
  }))
}
